name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install dependencies
        run: mvn install

      - name: Build project
        run: mvn clean package

      - name: Run tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy application
        run: |
          echo "Deploying to remote server..."
          ssh user@your-server "cd /path/to/app && git pull && ./restart.sh"
